//APP
export const CLOSE_PAYINFO = "CLOSE_PAYINFO";
export const SHOW_PAYINFO = "SHOW_PAYINFO";
export const LIST_PAY_INFO = "LIST_PAY_INFO";
export const LISTING_PAY_INFO = "LISTING_PAY_INFO";
export const LISTPAYINFO_DUPLICATE="LISTPAYINFO_DUPLICATE";
export const LIST_PAY_ERROR = "LIST_PAY_ERROR";
export const LISTPAYINFO_CLEAR_ERROR = "LISTPAYINFO_CLEAR_ERROR";
export const LISTPAYINFO = "LISTPAYINFO";
export const SEARCH_PAYINFO_ERROR = "SEARCH_PAYINFO_ERROR";
export const SEARCH_PAYINFO_LOAD_MORE="SEARCH_PAYINFO_LOAD_MORE";
export const RESET_APPSTATE="RESET_APPSTATE";
//Fetch API
export const FETCH_CATCH = "FETCH_CATCH";
//authen
export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_EROR = "LOGIN_EROR";
export const LOGING = "LOGING";
export const LOGGED_IN = "LOGGED_IN";
export const LOGGED_OUT = "LOGGED_OUT";
export const EXPORT_FORM = "EXPORT_FORM";
export const AUTHEN_EXPRI = "AUTHEN_EXPRI";
//navigation
export const PUSH_ROUTE = "PUSH_ROUTE";
export const POP_ROUTE = "POP_ROUTE";
export const RESET_ROUTE = "RESET_ROUTE";
//drawer navigation
export const DRAWEROPEN = "DRAWEROPEN";
export const DRAWERCLOSE = "DRAWERCLOSE";
//
export const DEFAULT = "DEFAULT";
//search actions
export const LIST_RESULT = "LIST_RESULT";
export const SEARCHING = "SEARCHING";
export const SEARCH_ERROR = "SEARCH_ERROR";
export const SEARCH_FETCH_ERROR = "SEARCH_FETCH_ERROR";
export const SEARCH_RESET = "SEARCH_RESET";
export const SEARCH_LOAD_MORE = "SEARCH_LOAD_MORE";
export const SEARCH_CLEAR_ERROR = "SEARCH_CLEAR_ERROR";
//user info
export const USER_INFO = "USER_INFO";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAIL = "CHANGE_PASSWORD_FAIL";
export const RESET_USER = "RESET_USER";

//bill list
export const BALANCE = "BALANCE";
export const BILL_LIST = "BILL_LIST";
export const BILL_LISTING = "BILL_LISTING";
export const BILLLIST_DUPLICATE="BILLLIST_DUPLICATE";
export const LIST_ERROR = "LIST_ERROR";
export const BILL_LIST_FETCH_CATCH = "BILL_LIST_FETCH_CATCH";
export const LIST_RESET = "LIST_RESET";
export const BILL_LIST_LOADMORE = "BILL_LIST_LOADMORE";
export const BILL_FROM_ID = "BILL_FROM_ID";
export const LIST_BILL_PAY_ERROR = "LIST_BILL_PAY_ERROR";
export const BILL_LIST_CLEAR_ERROR = "BILL_LIST_CLEAR_ERROR";
//bill detail
export const BILL_PAY = "BILL_PAY";
export const BILL_PAYING = "BILL_PAYING";
export const BILL_PAY_ERROR = "BILL_PAY_ERROR";
export const BILL_DETAIL_FETCH_CATCH = "BILL_DETAIL_FETCH_CATCH";
export const BILL_DETAIL_CLEAR_ERROR = "BILL_DETAIL_CLEAR_ERROR";
//history
export const HISTORYING = "HISTORYING";
export const HISTORY = "HISTORY";
export const HISTORY_ERROR = "HISTORY_ERROR";
export const HISTORY_FETCH_CATCH = "HISTORY_FETCH_CATCH";
export const HISTORY_CLEAR_ERROR = "HISTORY_CLEAR_ERROR";
